### ISSUE TITLE
unable to parse MASTER NEXUS output

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/latency-model#2]
Because rcolgem doesn't annotate coalescent tree simulations with state transitions (deme migrations), I am using MASTER to simulate trees under the simple Rong-Perelson model.  As of commit 7c950dbfc1270c9bd2454cac954cc30fc54cdf6c, the NEXUS output looks like what I expect.  However, I can't parse this output with either FigTree or BioPython.  

BioPython throws the following exception:
```
>>> tree = Phylo.read('RPTree_output.nexus', 'nexus')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Phylo/_io.py", line 63, in read
    tree = next(tree_gen)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Phylo/_io.py", line 51, in parse
    for tree in getattr(supported_formats[format], 'parse')(fp, **kwargs):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Phylo/NexusIO.py", line 38, in parse
    nex = Nexus.Nexus(handle)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Nexus/Nexus.py", line 604, in __init__
    self.read(input)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Nexus/Nexus.py", line 655, in read
    self._parse_nexus_block(title, contents)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Nexus/Nexus.py", line 696, in _parse_nexus_block
    getattr(self, '_' + line.command)(line.options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Nexus/Nexus.py", line 1085, in _tree
    tree=opts.rest().strip())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Nexus/Trees.py", line 70, in __init__
    subtree_info, base_info = self._parse(tree)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Nexus/Trees.py", line 112, in _parse
    subclades = [self._parse(subtree) for subtree in subtrees]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Nexus/Trees.py", line 97, in _parse
    val = self._get_values(tree[closing + 1:])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Bio/Nexus/Trees.py", line 164, in _get_values
    % (NODECOMMENT_START, NODECOMMENT_END))
Bio.Nexus.Trees.TreeError: Error in tree description: Found [& without matching ]
```

**Comment by ArtPoon** [comment]
The problem was seeding the simulation with multiple lineages instead of one.  The NEXUS file contained a multiple trees delimited by commas (which is a pretty lousy choice) due to the population descending from 10 completely unrelated free viruses.  Switching back to a single lineage free virus resolved the problem.
